/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.vitorsantana.cmsptasksdoer;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author vitor
 */
public class LoginWarning extends javax.swing.JDialog{
    
    OptionsDialog optionsDialog;

    /**
     * Creates new form LoginWarning
     */
    public LoginWarning(java.awt.Frame parent, boolean modal){
        super(parent, modal);
                try{
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
                if("Windows".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch(ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex){
            java.util.logging.Logger.getLogger(LoginWarning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        progressInfo.setText("");
        optionsDialog = new OptionsDialog((Frame) getParent(), true);
    }
    
    public void setNameAndNick(String name, String nick){
        warningUserText.setText(warningUserText.getText().replace("[USERNAME]", name));
        this.setSize(warningUserText.getX()+warningUserText.getPreferredSize().width, this.getHeight());
        nickName.setText(nick);
        tasksNumber.setText(""+CMSPTasksDoer.cmspCommunicator.getTasks().size());
        progressBar.setSize(146, 14);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warningUserText = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        progressInfo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nickName = new javax.swing.JLabel();
        tasksNumber = new javax.swing.JLabel();
        doTasks = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        optionsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informação de conta");
        setBounds(0,0,0,warningUserText.getPreferredSize().width);
        setMinimumSize(new java.awt.Dimension(533, 235));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        warningUserText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        warningUserText.setText("Bem vindo(a) [USERNAME]!");

        progressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        progressBar.setMaximumSize(new java.awt.Dimension(146, 14));
        progressBar.setMinimumSize(new java.awt.Dimension(146, 14));
        progressBar.setStringPainted(true);

        progressInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progressInfo.setText("progressInfo");
        progressInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setText("Nick:");

        jLabel4.setText("Quantidade restante:");

        nickName.setText("SeidyNadaNao");

        tasksNumber.setText("Muitas");

        doTasks.setText("Realizar tarefas");

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        optionsButton.setText("Opções");
        optionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("   ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tasksNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nickName)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(warningUserText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(progressInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(doTasks)
                                .addGap(66, 66, 66)
                                .addComponent(optionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(64, 64, 64)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, doTasks});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(warningUserText))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nickName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tasksNumber))
                .addGap(14, 14, 14)
                .addComponent(progressInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doTasks)
                    .addComponent(cancelButton)
                    .addComponent(optionsButton))
                .addGap(5, 5, 5))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        
        System.out.println("Typed");
        KeyStroke.getKeyStroke('i');
        
        if(this.getComponent(0).getIgnoreRepaint()){
            
        }
    }//GEN-LAST:event_formKeyTyped

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        System.out.println("Realesed");
    }//GEN-LAST:event_formKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        EnterTaskId enterTaskId = new EnterTaskId((Frame) getParent(), true);
            enterTaskId.taskId.addActionListener((ActionEvent e) -> {
                    System.out.println("ACTION");
                    if(enterTaskId.taskId.getText().isEmpty() || enterTaskId.taskId.getText().isBlank()){
                        enterTaskId.dispose();
                        return;
                    }
                    CMSPTasksDoer.addTaskById(Long.parseLong(enterTaskId.taskId.getText()));
                    tasksNumber.setText(""+CMSPTasksDoer.cmspCommunicator.getTasks().size());
                    pack();
                    enterTaskId.dispose();
            });
            enterTaskId.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void optionsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        optionsDialog.setVisible(true);
    }                                             


//        java.awt.EventQueue.invokeLater(new Runnable(){
//            public void run(){
//                LoginWarning dialog = new LoginWarning(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter(){
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e){
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelButton;
    public javax.swing.JButton doTasks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nickName;
    private javax.swing.JButton optionsButton;
    public javax.swing.JProgressBar progressBar;
    public javax.swing.JLabel progressInfo;
    private javax.swing.JLabel tasksNumber;
    private javax.swing.JLabel warningUserText;
    // End of variables declaration//GEN-END:variables
}
